# Generated by Django 2.2.3 on 2019-08-01 10:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190717_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], max_length=400, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If button page is not selected then it will default here', required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=50, required=True))]))], blank=True, null=True),
        ),
    ]
